/**
 * Generated by Reactium
 * DO NOT directly edit this file !!!!!!
 */

module.exports = {
    domains: {
        API: { name: 'API', implied: 'api', original: 'src/app/api/domain.js' },
        StateLoader: {
            name: 'StateLoader',
            implied: 'StateLoader',
            original:
                'src/app/components/Test/StateLoader/reactium-domain-stateloader.js',
        },
        LoadingSpinner: {
            name: 'LoadingSpinner',
            implied: 'Loading',
            original:
                'reactium_modules/@atomic-reactor/reactium-core/components/Loading/reactium-domain-Loading.js',
        },
    },
    relative: {
        'src/app/api': 'API',
        'src/app/components/Test/StateLoader': 'StateLoader',
        'reactium_modules/@atomic-reactor/reactium-core/components/Loading':
            'LoadingSpinner',
    },
};
